-- Ticket 639187
-- Atualiza comprador para Importados INDI 370

BEGIN
  FOR fam IN (SELECT DISTINCT F.SEQFAMILIA 
                FROM MAP_FAMDIVISAO C INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = C.SEQFAMILIA
                                      INNER JOIN MAX_COMPRADOR O ON O.SEQCOMPRADOR = C.SEQCOMPRADOR
                
               WHERE C.SEQFAMILIA IN (SELECT SEQFAMILIA FROM NAGT_BASE_639187 A INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = A.SEQPRODUTO)
                 AND C.SEQCOMPRADOR != 370)
  LOOP
    UPDATE MAP_FAMDIVISAO X
       SET X.SEQCOMPRADOR = 370, -- Imp Indireta
           X.USUARIOALTERACAO = 'TKT639187',
           X.DTAHORALTERACAO = SYSDATE
     WHERE X.SEQFAMILIA = fam.SEQFAMILIA;
  END LOOP;
  COMMIT;
END;
