CREATE TABLE NAGT_BACKUP_GLN_NOMEECOMM AS

SELECT A.SEQPRODUTO,
       A.NOMEPRODUTOECOMM ANTIGO,
       B.NOMEPRODUTOECOMM NOVO_NOME
  FROM MAP_PRODUTO A INNER JOIN NAGT_DEPARAGLN B
    ON A.SEQPRODUTO = B.SEQPRODUTO;
    

DECLARE 
    i INTEGER := 0;
BEGIN
    
    FOR t IN (SELECT A.SEQPRODUTO,
                     A.NOMEPRODUTOECOMM ANTIGO,
                     B.NOMEPRODUTOECOMM NOVO_NOME
                FROM MAP_PRODUTO A INNER JOIN NAGT_DEPARAGLN B ON A.SEQPRODUTO = B.SEQPRODUTO AND A.NOMEPRODUTOECOMM != B.NOMEPRODUTOECOMM)
                
    LOOP
    i := i+1;
    UPDATE MAP_PRODUTO P SET P.NOMEPRODUTOECOMM = T.NOVO_NOME,
                             P.USUARIOALTERACAO = 'AT_DESC_HUM',
                             P.DTAHORALTERACAO = SYSDATE
                       WHERE P.SEQPRODUTO = T.SEQPRODUTO;
    IF i = 500
      THEN COMMIT;
    i := 0;
    END IF;
    END LOOP;
    
END;

