-- Ticket 676170
-- Altera o regime do distribuidor para fabricante

CREATE TABLE NAGT_BKP_676170 AS

SELECT X.SEQFORNECEDOR, NOMERAZAO, TIPFORNECEDOR, FD.NROREGTRIBUTACAO NROREGIME, FD.NROREGTRIBUTIMPORTACAO NROREGIMERES13
  FROM MAF_FORNECEDOR X INNER JOIN MAF_FORNECDIVISAO FD ON FD.SEQFORNECEDOR = X.SEQFORNECEDOR
                        INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQFORNECEDOR
                        
 WHERE X.TIPFORNECEDOR = 'D'
   AND (NROREGTRIBUTACAO != 2 OR NROREGTRIBUTIMPORTACAO != 2)
   AND X.SEQFORNECEDOR > 999;
   
BEGIN
  FOR t IN (SELECT X.SEQFORNECEDOR, TIPFORNECEDOR, FD.NROREGTRIBUTACAO, FD.NROREGTRIBUTIMPORTACAO 
              FROM MAF_FORNECEDOR X INNER JOIN MAF_FORNECDIVISAO FD ON FD.SEQFORNECEDOR = X.SEQFORNECEDOR
                                    INNER JOIN NAGT_FORNECREGIME0 R ON R.SEQFORNECEDOR = X.SEQFORNECEDOR
             WHERE X.TIPFORNECEDOR = 'D'
               AND (NROREGTRIBUTACAO != 2 OR NROREGTRIBUTIMPORTACAO != 2)
               AND X.SEQFORNECEDOR > 999)
   
   LOOP
   
   UPDATE MAF_FORNECDIVISAO FD SET NROREGTRIBUTACAO = 2, NROREGTRIBUTIMPORTACAO = 2 WHERE SEQFORNECEDOR = t.SEQFORNECEDOR;
   
   END LOOP;
   
COMMIT;
END;

CREATE TABLE NAGT_FORNECREGIME0 (SEQFORNECEDOR NUMBER(30))
SELECT * FROM NAGT_FORNECREGIME0;
