CREATE TABLE NAGT_TKT_676932 (NROTRIBUTACAO NUMBER(4));
 SELECT * FROM NAGT_TKT_676932 FOR UPDATE;
   
CREATE TABLE NAGT_TKT_676932_BKP AS
SELECT X.NROTRIBUTACAO, X.TIPTRIBUTACAO, X.UFEMPRESA, X.UFCLIENTEFORNEC, X.NROREGTRIBUTACAO, X.INDAPROPRIAST, X.SITUACAONFDEV
  FROM MAP_TRIBUTACAOUF X
  
 WHERE 1=1
   AND EXISTS (SELECT 1 FROM NAGT_TKT_676932 A WHERE A.NROTRIBUTACAO = X.NROTRIBUTACAO)
   AND X.NROREGTRIBUTACAO IN (0,2,7)
   AND X.TIPTRIBUTACAO    IN ('EI','EM')
   AND UFEMPRESA       = 'RJ'
   AND UFCLIENTEFORNEC = 'SP'
   AND (SITUACAONFDEV != '000' OR INDAPROPRIAST != 'O');
   
BEGIN
  FOR t IN ( SELECT * FROM NAGT_TKT_676932_BKP) LOOP
    UPDATE MAP_TRIBUTACAOUF X SET X.DTAALTERACAO = SYSDATE, X.USUALTERACAO = 'TKT676932',
                                  X.SITUACAONFDEV = '000',
                                  X.INDAPROPRIAST = 'O'
                            WHERE X.NROTRIBUTACAO = t.Nrotributacao
                              AND X.TIPTRIBUTACAO = t.Tiptributacao
                              AND X.UFCLIENTEFORNEC = t.Ufclientefornec
                              AND X.UFEMPRESA = t.Ufempresa
                              AND X.NROREGTRIBUTACAO = t.Nroregtributacao;
  END LOOP;
END;
