-- Ticket 678083

-- Atualiza requisicoes com saldo
BEGIN
  FOR req IN (
SELECT X.NROREQUISICAO, SEQREQUISICAO,
       X.VALOR - (SELECT NVL(SUM(A.VALOR), 0)
                    FROM OR_NFDESPESA A, OR_NFDESPESAREQ B
                   WHERE A.SEQNOTA = B.SEQNOTA
                     AND B.SEQREQUISICAO = X.SEQREQUISICAO) SALDO,
       X.NROEMPRESA,
       X.CODMODELO
  FROM OR_REQUISICAO X
 INNER JOIN RF_PARAMNATNFDESP O
    ON O.CODHISTORICO = X.CODHISTORICO

 WHERE 1 = 1
   AND O.CGO = 6
   AND CODMODELO = '99'
      -- So o que tem saldo
   AND X.VALOR - (SELECT NVL(SUM(A.VALOR), 0)
                    FROM OR_NFDESPESA A, OR_NFDESPESAREQ B
                   WHERE A.SEQNOTA = B.SEQNOTA
                     AND B.SEQREQUISICAO = X.SEQREQUISICAO) > 0
      -- Dentro de 1 ano
   AND X.DTAINCLUSAO >= SYSDATE - 365)
   
   LOOP
     UPDATE OR_REQUISICAO R SET R.CODMODELO = 'NF' WHERE R.SEQREQUISICAO = req.SEQREQUISICAO;
   COMMIT;
   END LOOP;
 END;

-- Atualiza parametro da nat

UPDATE RF_PARAMNATNFDESP
   SET MODELONF = 'NF', TIPOMODELONF = 'NFSe'
 WHERE CGO = 6
   AND MODELONF = 99;
   COMMIT;

