DECLARE
      i INTEGER := 0;
      
      BEGIN
        FOR t IN (SELECT DISTINCT  Z.SEQFAMILIA, X.QTDEMBALAGEM, X.STATUSVENDA, X.SEQPRODUTO
                    FROM CONSINCO.MRL_PRODEMPSEG X INNER JOIN CONSINCO.MAP_PRODUTO Y ON (X.SEQPRODUTO = Y.SEQPRODUTO)
                                                   INNER JOIN CONSINCO.MAP_FAMILIA Z ON (Z.SEQFAMILIA = Y.SEQFAMILIA)                  
                WHERE NOT EXISTS (SELECT * FROM CONSINCO.MAP_FAMEMBALAGEM K WHERE K.SEQFAMILIA = Z.SEQFAMILIA AND K.QTDEMBALAGEM = X.QTDEMBALAGEM) AND STATUSVENDA = 'A')
    LOOP
      BEGIN
        i := i+1;
        UPDATE CONSINCO.MRL_PRODEMPSEG A SET STATUSVENDA = 'I'
                                       WHERE A.SEQPRODUTO = T.SEQPRODUTO 
                                         AND A.QTDEMBALAGEM = T.QTDEMBALAGEM;
      IF i = 10 THEN COMMIT;
      i := 0;
      END IF;
      
      EXCEPTION
        WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERRO: '||T.SEQPRODUTO);
      END;
     END LOOP;
    COMMIT;
   END;
   
