-- Cancela pedido em separacao
-- Passar empresa/prod no select do loop

BEGIN
  FOR t IN (SELECT A.NROPEDVENDA, A.NROEMPRESA
       
  FROM MADV_COMPOSICAORESERVAVDA A INNER JOIN MAD_PEDVENDA B ON A.NROPEDVENDA = B.NROPEDVENDA

 WHERE 1 = 1
       AND (A.SEQPRODUTOBASE = '269417' OR (A.SEQPRODUTO = '269417' 
       AND A.SEQPRODUTOBASE IS NULL))
       AND A.NROEMPRESAESTQ = '503')
       
       LOOP
          UPDATE MAD_PEDVENDA D SET SITUACAOPED = 'D'
                      WHERE D.NROPEDVENDA = t.NROPEDVENDA
                        AND D.NROEMPRESA =  T.NROEMPRESA;
 
                        
    UPDATE CONSINCO.MAD_PEDVENDAITEM B
       SET B.QTDATENDIDA = 0
     WHERE B.NROPEDVENDA = T.NROPEDVENDA;
  
    UPDATE CONSINCO.MAD_PEDVENDA
       SET SITUACAOPED     = 'C',
           DTACANCELAMENTO = SYSDATE,
           USUCANCELAMENTO = 'CANC_IMP',
           MOTCANCELAMENTO = 'Cancelamento Ped Sep',
           OBSCANCELAMENTO = 'MANUAL - GIULIANO',
           INDREPLICAFV    = 'S'
     WHERE NROPEDVENDA = T.NROPEDVENDA
       AND MAD_PEDVENDA.NROEMPRESA = t.NROPEDVENDA;
  
  END LOOP;
  
END;

