DECLARE
      i INTEGER := 0;
      
      BEGIN
        FOR t IN (SELECT A.* FROM CONSINCO.MRL_RECEITARENDTO A WHERE NVL(A.INDUTILPRODCOMPINV,'N') = 'N')
          
    LOOP
      BEGIN
        i := i+1;
        UPDATE CONSINCO.MRL_RECEITARENDTO X SET INDUTILPRODCOMPINV = 'S'
                                          WHERE X.SEQRECEITARENDTO = T.SEQRECEITARENDTO;
      IF i = 10 THEN COMMIT;
      i := 0;
      END IF;
      
      EXCEPTION
        WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERRO: '||T.SEQRECEITARENDTO);
      END;
     END LOOP;
    COMMIT;
   END;
   
SELECT COUNT(1)FROM CONSINCO.MRL_RECEITARENDTO X WHERE NVL(X.INDUTILPRODCOMPINV,'N') ='N'
