ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

BEGIN 
  
FOR t IN(

SELECT SEQPESSOA, NOMERAZAO, INSCRICAORG IE, X.INDCONTRIBICMS
  FROM GE_PESSOA X
 WHERE 1=1 --X.SEQPESSOA = 172584
   AND UPPER(REPLACE(X.INSCRICAORG, ' ', '')) LIKE '%ISENTO%'
   AND NVL(X.INDCONTRIBICMS, 'N') = 'S'    

)

LOOP 
UPDATE GE_PESSOA A SET A.INDCONTRIBICMS = 'N',
                       A.USUALTERACAO = 'TKT492733'
                       
WHERE A.SEQPESSOA = T.SEQPESSOA;

END LOOP;
END;

SELECT SEQPESSOA, NOMERAZAO, INSCRICAORG IE, X.INDCONTRIBICMS
  FROM GE_PESSOA X
 WHERE 1=1 --X.SEQPESSOA = 172584
   AND X.USUALTERACAO = 'TKT492733'
