-- Ticket 556388
--- Cria os Backups

CREATE TABLE CONSINCO.NAGT_MAP_PAUTAUFLOG_556388 AS
SELECT * FROM MAP_PAUTAUFLOG A;
             
CREATE TABLE CONSINCO.NAGT_MAP_PAUTAUF_556388 AS
SELECT * FROM MAP_PAUTAUF B;

-- Processa as Pautas e apaga as indevidas

BEGIN
  FOR t IN (SELECT * FROM MAP_PAUTAUFLOG A
             WHERE 1=1
               AND A.NROREGTRIBUTACAO NOT IN (0,2,7))
               
  LOOP
    DELETE FROM MAP_PAUTAUF Y WHERE Y.SEQPAUTA = T.SEQPAUTA AND Y.NROREGTRIBUTACAO = T.NROREGTRIBUTACAO;
    DELETE FROM MAP_PAUTAUFLOG X 
                          WHERE X.SEQPAUTAUFLOG = T.SEQPAUTAUFLOG
                            AND X.SEQPAUTA = T.SEQPAUTA
                            AND X.NROREGTRIBUTACAO = T.NROREGTRIBUTACAO
                            AND X.UFORIGEM = T.UFORIGEM
                            AND X.UFDESTINO = T.UFDESTINO
                            AND X.DTAINICIO = T.DTAINICIO;
          COMMIT;                  
   END LOOP;
   
END;
                    
-- Volta Backup

DELETE FROM MAP_PAUTAUF WHERE 1=1;
DELETE FROM MAP_PAUTAUFLOG WHERE 2=2;

INSERT INTO MAP_PAUTAUFLOG SELECT * FROM NAGT_MAP_PAUTAUFLOG_556388;
INSERT INTO MAP_PAUTAUF SELECT * FROM NAGT_MAP_PAUTAUF_556388 XX WHERE EXISTS (SELECT 2 FROM MAP_PAUTAUFLOG Z WHERE Z.SEQPAUTAUFLOG = XX.SEQPAUTAUFLOG);

SELECT COUNT(1) FROM MAP_PAUTAUF;
SELECT COUNT(1) FROM NAGT_MAP_PAUTAUF_556388;

SELECT COUNT(1) FROM MAP_PAUTAUFLOG;
SELECT COUNT(1) FROM NAGT_backup_556388;
