CREATE TABLE NAGT_BACKUP_DATANASC AS

SELECT GE.DTANASCFUND, TO_DATE(TO_CHAR(A.DATA_NASCIMENTO, 'DD/MM/YYYY'), 'DD/MM/YYYY') DATA_NASCIMENTO, CPF_CNPJ, GE.SEQPESSOA
  FROM APP_CUSTOMER@CONSINCODW A
 INNER JOIN CONSINCO.GE_PESSOA GE
    ON (LPAD(GE.NROCGCCPF, 12, 0) || LPAD(GE.DIGCGCCPF, 2, 0) =
       LPAD(A.CPF_CNPJ, 14, 0) AND GE.FISICAJURIDICA = 'F')
 WHERE 1 = 1
       AND GE.DTANASCFUND != TO_DATE(TO_CHAR(A.DATA_NASCIMENTO, 'DD/MM/YYYY'), 'DD/MM/YYYY');
       
BEGIN
  DECLARE 
    i INTEGER := 0;
    total INTEGER := 0;
    
BEGIN
  FOR t IN (

SELECT GE.DTANASCFUND, TO_DATE(TO_CHAR(A.DATA_NASCIMENTO, 'DD/MM/YYYY'), 'DD/MM/YYYY') DATA_NASCIMENTO, CPF_CNPJ, GE.SEQPESSOA
  FROM APP_CUSTOMER@CONSINCODW A
 INNER JOIN CONSINCO.GE_PESSOA GE
    ON (LPAD(GE.NROCGCCPF, 12, 0) || LPAD(GE.DIGCGCCPF, 2, 0) =
       LPAD(A.CPF_CNPJ, 14, 0) AND GE.FISICAJURIDICA = 'F')
 WHERE 1 = 1
       AND GE.DTANASCFUND != TO_DATE(TO_CHAR(A.DATA_NASCIMENTO, 'DD/MM/YYYY'), 'DD/MM/YYYY'))
       
       LOOP
         i := i + 1;
       
       UPDATE GE_PESSOA G SET DTANASCFUND = TO_DATE(TO_CHAR(T.DATA_NASCIMENTO, 'DD/MM/YYYY'), 'DD/MM/YYYY'),
                              G.USUALTERACAO = 'C_NASC_CRM'
                        WHERE G.SEQPESSOA = T.SEQPESSOA;

        
        IF i = 100 THEN -- Define o Commit por quantidade de linhas
            COMMIT;
            i := 0;
        END IF;
    END LOOP;
COMMIT;
END;
END;
