BEGIN
  DECLARE 
    i INTEGER := 0;
    
  BEGIN
  FOR T IN (SELECT * FROM NAGT_BASE_DESCHUM)
  
  LOOP
    i := i + 1;
    UPDATE MAP_PRODUTO P
       SET P.DTAHORALTERACAO  = TRUNC(SYSDATE - 10),
           P.USUARIOALTERACAO = 'ALT_CRM',
           P.DESCECOMMERCE    = T.DESC_ECOMM,
           P.NOMEPRODUTOECOMM = T.NOME_ECOMM,
           P.INDINTEGRAECOMMERCE = 'S'
           
     WHERE P.SEQPRODUTO = T.SEQPRODUTO;
        IF i = 100 THEN 
            i := 0;
        END IF;
  END LOOP;
 END;
END;

SELECT P.SEQPRODUTO, P.DESCECOMMERCE, P.NOMEPRODUTOECOMM FROM MAP_PRODUTO P INNER JOIN NAGT_BASE_DESCHUM X ON X.SEQPRODUTO = P.SEQPRODUTO
 
