CREATE TABLE CONSINCO.NAGT_MAP_PRODCODIGO_TRIBNFE AS

SELECT X.SEQPRODUTO, DESCCOMPLETA, CODACESSO, Z.INDEANTRIBNFE
          FROM CONSINCO.MAP_PRODUTO X INNER JOIN CONSINCO.MAP_PRODCODIGO Z ON Z.SEQPRODUTO = X.SEQPRODUTO AND Z.TIPCODIGO = 'E'
         WHERE 1=1 
           AND NVL(Z.INDEANTRIBNFE,'N') = 'N'
         
--=======--
   
DECLARE
 i INTEGER := 0;
 BEGIN
   
   FOR t IN (
        SELECT X.SEQPRODUTO, DESCCOMPLETA, CODACESSO, Z.INDEANTRIBNFE
          FROM CONSINCO.MAP_PRODUTO X INNER JOIN CONSINCO.MAP_PRODCODIGO Z ON Z.SEQPRODUTO = X.SEQPRODUTO AND Z.TIPCODIGO = 'E'
         WHERE 1=1 
           AND NVL(Z.INDEANTRIBNFE,'N') = 'N'
            )
    LOOP
      
 BEGIN
       i := i+1;
       UPDATE CONSINCO.MAP_PRODCODIGO A SET A.INDEANTRIBNFE = 'S' 
                                      WHERE A.SEQPRODUTO  = T.SEQPRODUTO
                                        AND A.CODACESSO   = T.CODACESSO
                                        AND A.TIPCODIGO = 'E';
       IF i = 10 THEN COMMIT;
       i:= 0;
       END IF;
       END;
       
   END LOOP;
   
   COMMIT;
END;  
