ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE TABLE CONSINCO.NAGT_TKT431411 AS

SELECT DISTINCT b.SEQPRODUTO, LPAD(CGCFORNEC,7,0) CGCFORNEC
      
  FROM CONSINCO.MLF_NOTAFISCAL X INNER JOIN CONSINCO.MLF_NFITEM B ON X.SEQNF = B.SEQNF
                                 INNER JOIN TMP_M000_NF K         ON K.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                                 INNER JOIN TMP_M014_ITEM L       ON L.M000_ID_NF  = K.M000_ID_NF  AND L.M014_NR_ITEM = B.SEQITEMNFXML
                                 INNER JOIN GE_PESSOA G           ON G.SEQPESSOA   = X.SEQPESSOA
                                 INNER JOIN MAP_PRODCODIGO X2     ON X2.SEQPRODUTO = B.SEQPRODUTO AND LPAD(CGCFORNEC,7,0) = SUBSTR(G.NROCGCCPF,0,7) AND X2.CODACESSO = L.M014_CD_PRODUTO
                                 INNER JOIN MAP_PRODUTO P         ON P.SEQPRODUTO  = B.SEQPRODUTO
                                 INNER JOIN MAP_FAMILIA F         ON F.SEQFAMILIA  = P.SEQFAMILIA

WHERE 1=1 
  AND X.DTAEMISSAO BETWEEN DATE '2024-08-01' AND DATE '2024-08-31'
  AND NVL(F.PESAVEL, 'N') = 'N'
  AND L.M014_DS_UNID_COM LIKE 'UN%' 
  AND X2.QTDEMBALAGEM > 1
  AND X.SEQPESSOA > 999 
   
CREATE TABLE CONSINCO.NAGT_TKT431411BKP AS

SELECT X.*
  FROM MAP_PRODCODIGO X INNER JOIN NAGT_TKT431411 B ON X.SEQPRODUTO = B.SEQPRODUTO AND LPAD(X.CGCFORNEC,7,0) = LPAD(B.CGCFORNEC,7,0)
 WHERE 1=1
   AND X.TIPCODIGO = 'F'
   AND QTDEMBALAGEM > 1; 
 
SELECT * FROM NAGT_TKT431411BKP
 
DECLARE
  i INTEGER := 0;
  
  BEGIN
  FOR t IN (SELECT X.*
  FROM MAP_PRODCODIGO X INNER JOIN NAGT_TKT431411 B ON X.SEQPRODUTO = B.SEQPRODUTO AND LPAD(X.CGCFORNEC,7,0) = LPAD(B.CGCFORNEC,7,0)
 WHERE 1=1
   AND X.TIPCODIGO = 'F'
   AND QTDEMBALAGEM > 1)
  LOOP
    BEGIN
    i := i+1;
     UPDATE CONSINCO.MAP_PRODCODIGO X SET X.QTDEMBALAGEM = 1,
                                          X.USUARIOALTERACAO = 'TKT_431411'
                                    WHERE X.SEQPRODUTO   = T.SEQPRODUTO
                                      AND LPAD(X.CGCFORNEC,7,0) = LPAD(T.CGCFORNEC,7,0)
                                      AND X.TIPCODIGO    = T.TIPCODIGO
                                      AND X.CODACESSO    = T.CODACESSO;
                                      
                                      -- Atualiza pra subir pra iTworks
     UPDATE CONSINCO.MAP_PRODUTO Z SET Z.DTAHORALTERACAO  = SYSDATE,
                                       Z.USUARIOALTERACAO = 'TKT_431411'
                                 WHERE Z.SEQPRODUTO       = T.SEQPRODUTO;
                       
    IF i = 10 THEN COMMIT;
    i := 0;
    END IF;

    COMMIT;
    END;
    
  END LOOP;
  
  END;
