
-- Script para capturar e corrigir endereços que possuem saldos negativos e positivos, no mesmo end no WMS pois gera erro na validacao dos lotes de inventario

SELECT DISTINCT  E.NROEMPRESA, E.CODDEPOSITO, E.CODRUA, E.NROPREDIO, E.NROAPARTAMENTO, E.NROSALA
  FROM MLO_ENDERECOQTDE X INNER JOIN MLO_ENDERECO E ON E.SEQENDERECO = X.SEQENDERECO
 WHERE NVL(X.QTDATUAL,-1) < 0
   AND EXISTS (SELECT 1
                 FROM MLO_ENDERECOQTDE Y
                WHERE Y.SEQENDERECO = X.SEQENDERECO
                  AND NVL(QTDATUAL,1) > 0)
   AND EXISTS (SELECT 2
                 FROM MLO_LOTEINVFISITEM Z
                WHERE Z.SEQLOTE = 2952
                  AND Z.SEQENDERECO = X.SEQENDERECO)


BEGIN
  FOR t IN (

SELECT DISTINCT X.SEQENDERECO, E.NROEMPRESA, E.CODDEPOSITO, E.CODRUA, E.NROPREDIO, E.NROAPARTAMENTO, E.NROSALA, E.QTDATUAL, X.SEQENDERECOQTDE
  FROM MLO_ENDERECOQTDE X INNER JOIN MLO_ENDERECO E ON E.SEQENDERECO = X.SEQENDERECO
 WHERE X.QTDATUAL < 0
   AND EXISTS (SELECT 1
                 FROM MLO_ENDERECOQTDE Y
                WHERE Y.SEQENDERECO = X.SEQENDERECO
                  AND QTDATUAL > 0)
   AND EXISTS (SELECT 2
                 FROM MLO_LOTEINVFISITEM Z
                WHERE Z.SEQLOTE = 2952
                  AND Z.SEQENDERECO = X.SEQENDERECO)
                  
                  )
 LOOP
   UPDATE MLO_ENDERECOQTDE X SET X.QTDATUAL    = T.QTDATUAL
                           WHERE X.SEQENDERECO = T.SEQENDERECO;
                            -- AND ROW_NUMBER() OVER (PARTITION BY SEQENDERECO ORDER BY DTAVALIDADE DESC) = 1;
                             
   DELETE FROM MLO_ENDERECOQTDE X WHERE X.SEQENDERECO      = T.SEQENDERECO
                                    AND X.SEQENDERECOQTDE != T.SEQENDERECOQTDE;
 END LOOP;
 
END;

SELECT * FROM MLO_ENDERECO X WHERE EXISTS (SELECT 2
                 FROM MLO_LOTEINVFISITEM Z
                WHERE Z.SEQLOTE = 2952
                  AND Z.SEQENDERECO = X.SEQENDERECO) 
                  AND NOT EXISTS (SELECT 2 FROM MLO_ENDERECOQTDE E WHERE E.SEQENDERECO = X.SEQENDERECO)
                  
                  SELECT * FROM MLO_ENDERECOQTDE BB wHERE SEQENDERECO IN (704026,783548)
                  SELECT qTDATUAL, AA.* FROM MLO_ENDERECO AA wHERE AA.SEqPRODUTO =  210178 FOR UPDATE
                  
                  
