CREATE OR REPLACE PROCEDURE CONSINCO.NAGP_GERALOTECOMPRA AS
BEGIN
DECLARE
      i INTEGER := 0;

      BEGIN
        FOR t IN (SELECT D.SEQLOTEMODELO FROM CONSINCO.NAGV_BUSCADTAPEDIDO D 
                   WHERE SYSDATE > TO_DATE(TO_CHAR(D.DATA_VALIDA, 'DD/MM/YYYY')||' '||D.HORAMIN, 'DD/MM/YYYY HH24:MI')
                   ORDER BY HORAMIN ASC)

    LOOP
      BEGIN
      i := i+1;
      CONSINCO.NAGP_spMac_GeraLoteCompra(TRUNC(SYSDATE), 'N',t.SEQLOTEMODELO);
      IF i = 1 THEN COMMIT;
      i := 0;
      END IF;

      END;
     END LOOP;
    COMMIT;
   END;
END;
