CREATE OR REPLACE PROCEDURE NAGP_GERALOTEMOD AS
BEGIN
DECLARE
      i INTEGER := 0;

      BEGIN
        FOR t IN (SELECT D.SEQLOTEMODELO FROM NAGV_BUSCADTAPEDIDO D WHERE D.DATA_VALIDA <= SYSDATE)

    LOOP
      BEGIN
      i := i+1;
      NAGP_spMac_GeraLoteCompra(TRUNC(SYSDATE), 'N',t.SEQLOTEMODELO);
      IF i = 1 THEN COMMIT;
      i := 0;
      END IF;

      END;
     END LOOP;
    COMMIT;
   END;
END;
