CREATE OR REPLACE PROCEDURE NAGP_GERAPEDIDOABASTAUTO AS
BEGIN
DECLARE
      I INTEGER := 0;

      BEGIN -- SELECIONA OS LOTES DE ABASTECIMENTO EM ABERTO NO DIA ATUAL
        FOR T IN (SELECT DISTINCT A.SEQGERCOMPRA
                    FROM CONSINCO.MAC_GERCOMPRA A
                   WHERE 1=1
                    /*AND (A.TIPOLOTE = 'A' OR (A.TIPOLOTE = 'T' AND A.DTAVALIDADEMODINI IS NOT NULL AND A.DTAVALIDADEMODFIM IS NOT NULL ))*/
                     AND NVL(A.INDORDEMPRODFINALIZADA, 'S') = 'S'
                     AND A.TIPOLOTE = 'A'
                     AND TRUNC(A.DTAHORINCLUSAO) >= TRUNC(SYSDATE) AND TRUNC(A.DTAHORINCLUSAO) <= TRUNC(SYSDATE)
                     AND A.DTAHORFECHAMENTO IS NULL
                     AND NROEMPRESAGERALOTE IN (501,506))

    LOOP
      BEGIN
        I := I+1;

        UPDATE MAC_GERCOMPRA
           SET DTAHORFECHAMENTO = SYSDATE,
               USUFECHAMENTO    = 'JOBABASTAUTO',
               DTAGERPEDIDO     = TRUNC( SYSDATE ),
               USUGERPEDIDO     = 'JOBABASTAUTO',
               SITUACAOLOTE     = 'F',
               INCREMENTOMEDIAVENDA = NULL,
               TIPOSUGCOMPRA    = 'P',
               INDMINMAXQTD     = 'N',
               INDMINMAXDIAVDA  = 'N'
         WHERE SEQGERCOMPRA     = T.SEQGERCOMPRA;

         BEGIN PKG_ADM_COMPRA.SP_GERACARGAPEDVENDA(T.SEQGERCOMPRA, NULL,'S','A'); END;

         INSERT INTO NAGT_LOGGERAABASTAUTO VALUES (T.SEQGERCOMPRA, SYSDATE, 'JOBABASTAUTO', 'GERADO');

      IF I = 1 THEN COMMIT;
      I := 0;
      END IF;

      EXCEPTION
        WHEN OTHERS THEN
         INSERT INTO NAGT_LOGGERAABASTAUTO VALUES (T.SEQGERCOMPRA, SYSDATE, 'JOBABASTAUTO', 'ERRO');
      END;
     END LOOP;
    COMMIT;
   END;
   END;

---------
  
CREATE TABLE CONSINCO.NAGT_LOGGERAABASTAUTO 
      (SEQGERCOMPRA NUMBER(20),
       DTAGERACAO   DATE,
       USUGERACAO   VARCHAR2(20),
       SITUACAO     VARCHAR2(20));

----------

 BEGIN 
  NAGP_GERAPEDIDOABASTAUTO;
  END;
