BEGIN
  FOR t IN (
    
  SELECT DISTINCT NVL(C.NROACORDOAGRUP, X.NROACORDO) NROACORDO, NVL(C.NROEMPRESAACORDOAGRUP, X.NROEMPRESA) NROEMPRESA
  FROM MSU_ACORDOPROMOC X INNER JOIN MAC_TIPOACORDO A ON A.CODTIPOACORDO = X.CODTIPOACORDO
                           LEFT JOIN ESP_ACORDOPROMOCPEDIDO C ON C.NROACORDO = X.NROACORDO AND C.NROEMPRESA = X.NROEMPRESA
 WHERE 1=1
   AND X.SITUACAOACORDO = 'F'
   AND X.STATUSACORDO != 'C'
   -- Tira o que gerou financeiro direto 
   AND NOT EXISTS (SELECT 1 FROM FI_TITULO F WHERE F.NROTITULO = X.NROACORDO AND F.SEQPESSOA = X.SEQFORNECEDOR AND F.CODESPECIE = A.CODESPECIE AND F.SERIETITULO = 'ACO' AND X.DTAEMISSAO = F.DTAEMISSAO) 
   -- Tira filho que tem o pai no financeiro
   AND NOT EXISTS (SELECT 3 FROM ESP_ACORDOPROMOCPEDIDO E WHERE E.NROACORDO = X.NROACORDO AND EXISTS 
                 ((SELECT 3 FROM FI_TITULO F WHERE F.NROTITULO = E.NROACORDOAGRUP AND F.SEQPESSOA = X.SEQFORNECEDOR AND F.NROEMPRESA = E.NROEMPRESAACORDOAGRUP AND F.CODESPECIE = A.CODESPECIE)))

   AND X.DTAEMISSAO >= DATE '2025-08-01'
           )
   
   LOOP
   NAGP_INSERE_TIT_ACO(t.NROEMPRESA, t.NROACORDO);
   END LOOP;
 END;
