--SELECT * FROM MAP_PRODCODIGO X INNER JOIN MAP_FAMEMBALAGEM E ON E.SEQFAMILIA = X.SEQFAMILIA

CREATE TABLE NAGT_DEPARA_MEDIDAS (EAN NUMBER, ALTURA NUMBER(9,6), LARGURA NUMBER(9,6), PROFUNDIDADE NUMBER(9,6))

SELECT * FROM NAGT_DEPARA_MEDIDAS

CREATE TABLE MAP_FAMEMBALAGEM_BKP AS
SELECT * FROM MAP_FAMEMBALAGEM BK WHERE EXISTS (

SELECT DISTINCT SEQFAMILIA, ALTURA, LARGURA, PROFUNDIDADE FROM ( SELECT * 
  FROM (SELECT ROW_NUMBER() OVER(PARTITION BY SEQFAMILIA ORDER BY SEQFAMILIA) ODR,
               X.*
          FROM (SELECT DISTINCT B.SEQFAMILIA, --B.SEQPRODUTO,
                                A.ALTURA,
                                A.LARGURA,
                                A.PROFUNDIDADE
                  FROM NAGT_DEPARA_MEDIDAS A
                 INNER JOIN MAP_PRODCODIGO B
                    ON B.CODACESSO = TO_CHAR(A.EAN)
                 WHERE B.SEQPRODUTO IS NOT NULL) X)
 WHERE 1=1 AND ODR = 1
   AND BK.SEQFAMILIA = SEQFAMILIA
 --AND SEQFAMILIA = 3679
 ORDER BY 2  ));

-- Loop

BEGIN
  FOR t IN (

SELECT DISTINCT SEQFAMILIA, ALTURA, LARGURA, PROFUNDIDADE FROM ( SELECT * 
  FROM (SELECT ROW_NUMBER() OVER(PARTITION BY SEQFAMILIA ORDER BY SEQFAMILIA) ODR,
               X.*
          FROM (SELECT DISTINCT B.SEQFAMILIA, --B.SEQPRODUTO,
                                A.ALTURA,
                                A.LARGURA,
                                A.PROFUNDIDADE
                  FROM NAGT_DEPARA_MEDIDAS A
                 INNER JOIN MAP_PRODCODIGO B
                    ON B.CODACESSO = TO_CHAR(A.EAN)
                 WHERE B.SEQPRODUTO IS NOT NULL) X)
 WHERE 1=1 AND ODR = 1  
 --AND SEQFAMILIA = 3679
 ORDER BY 2  ))
 
 
 LOOP
 UPDATE 
 MAP_FAMEMBALAGEM UP SET UP.ALTURA       = T.ALTURA,
                         UP.LARGURA      = UP.QTDEMBALAGEM * T.LARGURA,
                         UP.PROFUNDIDADE = UP.QTDEMBALAGEM * T.PROFUNDIDADE,
                         UP.USUARIOALTERACAO = 'BASE_CSV_CAD'
                         WHERE UP.SEQFAMILIA = T.SEQFAMILIA
                          AND QTDEMBALAGEM = 1; -- Solicitado apenas emb 1
 END LOOP;
 
 END;
 
