ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;
     
BEGIN
  FOR t IN (

SELECT /*+OPTIMIZER_FEATURES_ENABLE('19.1.0')*/
       DISTINCT X.DTAINCLUSAO, X.NROPEDVENDA, X.SEQPESSOA EMP_DESTINO,
       XI.STATUSITEM, XI.SEQPRODUTO, (XI.QTDPEDIDA - QTDCORTEWM) QTD_TIRAR, XI.QTDATENDIDA, P.QTDSOLICITADA, XI.QTDPEDIDA, XI.QTDCORTEWM,
       X.NROCARGA, X.NROEMPRESA, X.USUINCLUSAO, X.USUCANCELAMENTO, XI.USUCANCELAMENTO USUCANC, P.USUCANCELAMENTO  USUCANC3
  FROM MAD_PEDVENDA X INNER JOIN MAD_PEDVENDAITEM XI ON XI.NROPEDVENDA = X.NROPEDVENDA AND XI.NROEMPRESA = X.NROEMPRESA
                      INNER JOIN MAX_EMPRESA      M  ON M.NROEMPRESA   = X.NROEMPRESA
                      INNER JOIN consinco.MLOV_CONTROLEETQSORTEREXPED P ON P.SEQPESSOA  = X.SEQPESSOA 
                                                                       AND P.NROCARGA   = X.NROCARGA
                                                                       AND P.SEQPRODUTO = XI.SEQPRODUTO
                             
 WHERE 1=1 
   --AND X.NROPEDVENDA = 7601579
   AND SUBSTR(P.SITUACAOETIQUETA, 1, 250) = 'Cancelada'
   AND X.SITUACAOPED != 'C'
   AND X.NROEMPRESA > 500
   --AND XI.QTDCORTEWM = P.QTDSOLICITADA
   AND XI.QTDATENDIDA > 0
   AND X.DTAINCLUSAO > DATE '2024-01-01'
   --AND (XI.QTDPEDIDA - QTDCORTEWM) = P.QTDSOLICITADA
   --AND XI.SEQPRODUTO = 248516
           
  ) 
   
   LOOP
   
   UPDATE MAD_PEDVENDAITEM A SET STATUSITEM = 'C',
                                 A.QTDATENDIDA = A.QTDATENDIDA - T.QTDSOLICITADA,
                                 A.USUCANCELAMENTO = 'TKT424721'
                           WHERE A.NROPEDVENDA = T.NROPEDVENDA
                             AND A.SEQPRODUTO  = T.SEQPRODUTO;
                                                  
   COMMIT;
   END LOOP;
   
   END;

--CREATE TABLE CONSINCO.NAGT_BKPRESERVACD AS
/*
SELECT \*+OPTIMIZER_FEATURES_ENABLE('19.1.0')*\ DISTINCT X.DTAINCLUSAO, X.NROPEDVENDA, X.SEQPESSOA EMP_DESTINO,
       XI.STATUSITEM, XI.SEQPRODUTO, (XI.QTDPEDIDA - QTDCORTEWM) QTD_TIRAR, XI.QTDATENDIDA, P.QTDSOLICITADA, XI.QTDPEDIDA, XI.QTDCORTEWM,
       X.NROCARGA, X.NROEMPRESA, X.USUINCLUSAO, X.USUCANCELAMENTO, XI.USUCANCELAMENTO USUCANC_ITEM, P.USUCANCELAMENTO USU_CANCWMS
  FROM MAD_PEDVENDA X INNER JOIN MAD_PEDVENDAITEM XI ON XI.NROPEDVENDA = X.NROPEDVENDA AND XI.NROEMPRESA = X.NROEMPRESA
                      INNER JOIN MAX_EMPRESA      M  ON M.NROEMPRESA   = X.NROEMPRESA
                      INNER JOIN consinco.MLOV_CONTROLEETQSORTEREXPED P ON P.SEQPESSOA  = X.SEQPESSOA 
                                                                       AND P.NROCARGA   = X.NROCARGA
                                                                       AND P.SEQPRODUTO = XI.SEQPRODUTO
                             
 WHERE 1=1 
   --AND X.NROPEDVENDA = 7601579
   AND SUBSTR(P.SITUACAOETIQUETA, 1, 250) = 'Cancelada'
   AND X.SITUACAOPED != 'C'
   AND X.NROEMPRESA > 500
   --AND XI.QTDCORTEWM = P.QTDSOLICITADA
   AND XI.QTDATENDIDA > 0
   AND X.DTAINCLUSAO > DATE '2024-01-01'
   --AND (XI.QTDPEDIDA - QTDCORTEWM) = P.QTDSOLICITADA
   --AND XI.SEQPRODUTO = 583749*/
   
--SELECT * FROM NAGT_BKPRESERVACD
