CREATE TABLE NAGT_BACKUP_CORRECAO_SEG_BK AS

SELECT *
  FROM MFL_DOCTOFISCAL X WHERE NROSEGMENTO = 10 AND NOT EXISTS (SELECT NROEMPRESA FROM MAX_EMPRESASEG S WHERE S.NROSEGMENTO = 10 AND X.NROEMPRESA = S.NROEMPRESA);

SELECT MIN(DTAMOVIMENTO), MAX(DTAMOVIMENTO) FROM NAGT_BACKUP_CORRECAO_SEG_BK;

BEGIN
  
FOR t IN 
  (SELECT SEQNF, NROSEGMENTOPRINC, DTAMOVIMENTO FROM NAGT_BACKUP_CORRECAO_SEG_BK BS INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = BS.NROEMPRESA)
  
  LOOP
    UPDATE MFL_DOCTOFISCAL X SET NROSEGMENTO    = t.NROSEGMENTOPRINC
                           WHERE X.SEQNF        = T.SEQNF 
                             AND X.DTAMOVIMENTO = T.DTAMOVIMENTO;
                             
  END LOOP; 
    
END;
 
