ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

DECLARE 
 i INTEGER := 0;
 
 BEGIN
   FOR t IN(

Select C1.NROCARGA, B1.NROPEDVENDA, A1.SITUACAOPED, B1.NROEMPRESA, B1.DTAINCLUSAO, SEQPRODUTO, QTDPEDIDA, QTDATENDIDA, QTDEXPEDIDA
      From   MAD_PEDVENDA A1,
             MAD_PEDVENDAITEM B1,
             MRL_CARGAEXPED C1
             
      Where  A1.NROEMPRESA = B1.NROEMPRESA
      And    A1.NROPEDVENDA = B1.NROPEDVENDA 
      And    A1.NROCARGA = C1.NROCARGA
      And    NVL(C1.INDGERAMOVESTOQUE, 'S') = 'S'
      And    C1.STATUSCARGA In ('S', 'L')
      AND A1.NROEMPRESA = 506
      AND QTDATENDIDA > 0
      AND QTDEXPEDIDA IS NULL 
      )
      
      LOOP
        BEGIN
          i := i+1;
          UPDATE MAD_PEDVENDAITEM X SET QTDATENDIDA = 0
                 WHERE X.SEQPRODUTO = T.SEQPRODUTO AND X.NROPEDVENDA = T.NROPEDVENDA AND X.NROEMPRESA = 506;
                 
                  IF i = 10 THEN COMMIT;
       i:= 0;
       END IF;
       
       EXCEPTION
         WHEN OTHERS THEN
           DBMS_OUTPUT.PUT_LINE('ERRO: '||T.SEQPRODUTO);
       END;
   END LOOP;
   COMMIT;
END;  
