-- Adicionar Atributo em 

  MAP_DESCESP
 
-- View de itens excluidos 

 CREATE OR REPLACE VIEW NAGV_PROD_EXCLUIDO_CAMP AS

SELECT A.TIPO, A.SEQPRODUTO, P.DESCCOMPLETA, B.CODACESSO CODIGO, B.TIPCODIGO
  FROM MAP_PRODDESCESP A INNER JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
                         INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = A.SEQPRODUTO
 WHERE A.TIPO = 'Item Excluido de Campanhas'
   AND B.TIPCODIGO != 'F';

SELECT * FROM MAP_PRODDESCESP;

-- Update dos produtos para adicionar o atributo

BEGIN
  FOR t IN (SELECT DISTINCT X.SEQPRODUTO, 'Item Excluido de Campanhas' TIPO, 1 CODIGO, 'CONSINCO' USUARIOALTERACAO
              FROM MAP_PRODCODIGO X
             WHERE EXISTS (SELECT 1 FROM NAGT_BASE_EXCLUSAO_CAMP A WHERE TO_CHAR(LPAD(A.CODPRODUTO,14,0)) = LPAD(X.CODACESSO,14,0))
               AND NOT EXISTS (SELECT 2 FROM MAP_PRODDESCESP B WHERE B.SEQPRODUTO = X.SEQPRODUTO))
    LOOP
      INSERT INTO MAP_PRODDESCESP VALUES (T.SEQPRODUTO, t.TIPO, t.CODIGO, t.USUARIOALTERACAO);
    END LOOP;
    
END;

-- Validando na view

SELECT * FROM NAGV_PROD_EXCLUIDO_CAMP

