CREATE TABLE CONSINCO.NAGT_DEPARA_TKT526413 (SEQPRODUTO NUMBER);

SELECT * FROM NAGT_DEPARA_TKT526413 FOR UPDATE;

BEGIN
  FOR t IN (SELECT SEQPRODUTO FROM NAGT_DEPARA_TKT526413)
    LOOP
      UPDATE MAP_PRODUTO X SET X.INDINTEGRAECOMMERCE = 'S',
                               X.PERSIMILIARECOMMERCE = 'S',
                               X.USUARIOALTERACAO = 'TKT526413',
                               X.DTAHORALTERACAO = SYSDATE
                               WHERE X.SEQPRODUTO = T.SEQPRODUTO;
    COMMIT;
    END LOOP;
    COMMIT;
END;

SELECT A.SEQPRODUTO, B.INDINTEGRAECOMMERCE, B.PERSIMILIARECOMMERCE FROM NAGT_DEPARA_TKT526413 A INNER JOIN MAP_PRODUTO B ON A.SEQPRODUTO = B.SEQPRODUTO
