CREATE TABLE NAGT_BKP_MULTECOMM AS

SELECT P.QTDMULTIPLOVDAECOMMERCE, SEQPRODUTO, DESCCOMPLETA, P.INDINTEGRAECOMMERCE FROM MAP_PRODUTO P WHERE P.QTDMULTIPLOVDAECOMMERCE IS NOT NULL;

SELECT * FROM NAGT_BKP_MULTECOMM

BEGIN

  FOR T IN (SELECT P.QTDMULTIPLOVDAECOMMERCE,
                   SEQPRODUTO,
                   DESCCOMPLETA,
                   P.INDINTEGRAECOMMERCE
              FROM MAP_PRODUTO P
             WHERE P.QTDMULTIPLOVDAECOMMERCE IS NOT NULL)
  LOOP
    UPDATE MAP_PRODUTO P
       SET P.QTDMULTIPLOVDAECOMMERCE = NULL
     WHERE P.SEQPRODUTO = T.SEQPRODUTO;
  END LOOP;

END;
